src/main/java/com/andaily/domain/dto/log/FrequencyMonitorLogDto.java
package com.andaily.domain.dto.log;

import com.andaily.domain.application.ApplicationInstance;
import com.andaily.domain.dto.AbstractDto;
import com.andaily.domain.log.FrequencyMonitorLog;
import com.andaily.infrastructure.DateUtils;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * 15-2-13
 *
 * @author Shengzhao Li
 */
public class FrequencyMonitorLogDto extends AbstractDto {

    private static final BigDecimal KB = new BigDecimal("1024");

    private String instanceGuid;
    private String instanceName;

    private boolean normal;
    private String createTime;
    private String createDate;

    private long costTime;
    private String remark;

    private long responseSize;

    public FrequencyMonitorLogDto() {
    }

    public FrequencyMonitorLogDto(FrequencyMonitorLog log) {
        super(log.guid());
        final Date time = log.createTime();
        this.createTime = DateUtils.toDateText(time, DateUtils.DEFAULT_DATE_TIME_FORMAT);
        this.createDate = DateUtils.toDateText(time);

        ApplicationInstance instance = log.instance();
        this.instanceGuid = instance.guid();
        this.instanceName = instance.instanceName();

        this.normal = log.normal();
        this.costTime = log.costTime();
        this.remark = log.remark();

        this.responseSize = log.responseSize();
    }

    public String getCreateDate() {
        return createDate;
    }

    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getInstanceGuid() {
        return instanceGuid;
    }

    public void setInstanceGuid(String instanceGuid) {
        this.instanceGuid = instanceGuid;
    }

    public String getInstanceName() {
        return instanceName;
    }

    public void setInstanceName(String instanceName) {
        this.instanceName = instanceName;
    }

    public boolean isNormal() {
        return normal;
    }

    public void setNormal(boolean normal) {
        this.normal = normal;
    }

    public long getCostTime() {
        return costTime;
    }

    public void setCostTime(long costTime) {
        this.costTime = costTime;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public long getResponseSize() {
        return responseSize;
    }

    public BigDecimal getResponseSizeAsKB() {
        return new BigDecimal(responseSize).divide(KB, 2, BigDecimal.ROUND_HALF_UP);
    }

    public void setResponseSize(long responseSize) {
        this.responseSize = responseSize;
    }

    public static List<FrequencyMonitorLogDto> toDtos(List<FrequencyMonitorLog> logs) {
        List<FrequencyMonitorLogDto> dtos = new ArrayList<>(logs.size());
        for (FrequencyMonitorLog log : logs) {
            dtos.add(new FrequencyMonitorLogDto(log));
        }
        return dtos;
    }
}

src/main/java/com/andaily/domain/dto/log/FrequencyMonitorLogListDto.java
package com.andaily.domain.dto.log;

import com.andaily.domain.dto.application.ApplicationInstanceDto;
import com.andaily.domain.shared.paginated.DefaultPaginated;
import com.andaily.infrastructure.grouper.GroupResult;
import com.andaily.infrastructure.grouper.impl.FrequencyMonitorLogDtoCreateTimeGrouper;
import org.apache.commons.lang.StringUtils;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * 15-2-13
 *
 * @author Shengzhao Li
 */
public class FrequencyMonitorLogListDto extends DefaultPaginated<FrequencyMonitorLogDto> {


    private String instanceGuid;
    //1 is normal,2 is not normal, otherwise all
    private int normal = 0;
    private OrderItem orderItem = OrderItem.LOG_TIME;

    private List<ApplicationInstanceDto> instanceDtos = new ArrayList<>();

    public FrequencyMonitorLogListDto() {
    }

    @Override
    public Map<String, Object> queryMap() {
        Map<String, Object> map = super.queryMap();
        map.put("instanceGuid", instanceGuid);
        map.put("normal", normal);
        map.put("orderItem", orderItem.getField());
        return map;
    }


    public List<GroupResult<String, FrequencyMonitorLogDto>> getListGroupResults() {
        FrequencyMonitorLogDtoCreateTimeGrouper grouper = new FrequencyMonitorLogDtoCreateTimeGrouper(list);
        return grouper.group().getGroupResults();
    }

    public OrderItem[] getOrderItems() {
        return OrderItem.values();
    }

    public ApplicationInstanceDto getInstanceDto() {
        if (StringUtils.isNotEmpty(instanceGuid)) {
            for (ApplicationInstanceDto instanceDto : instanceDtos) {
                if (instanceDto.getGuid().equals(instanceGuid)) {
                    return instanceDto;
                }
            }
        }
        return null;
    }

    public OrderItem getOrderItem() {
        return orderItem;
    }

    public void setOrderItem(OrderItem orderItem) {
        this.orderItem = orderItem;
    }

    public List<ApplicationInstanceDto> getInstanceDtos() {
        return instanceDtos;
    }

    public int getNormal() {
        return normal;
    }

    public void setNormal(int normal) {
        this.normal = normal;
    }

    public String getInstanceGuid() {
        return instanceGuid;
    }

    public void setInstanceGuid(String instanceGuid) {
        this.instanceGuid = instanceGuid;
    }


    /**
     * Order item
     */
    public static enum OrderItem {
        LOG_TIME("createTime", "Log Time"),
        CONN_TIME("costTime", "Conn Time");
        private String field;
        private String label;

        private OrderItem(String field, String label) {
            this.field = field;
            this.label = label;
        }

        public String getLabel() {
            return label;
        }

        public String getField() {
            return field;
        }

        public String getValue() {
            return name();
        }
    }

}

src/main/java/com/andaily/domain/dto/log/MonitoringReminderLogDto.java
package com.andaily.domain.dto.log;

import com.andaily.domain.application.ApplicationInstance;
import com.andaily.domain.dto.AbstractDto;
import com.andaily.domain.log.MonitoringReminderLog;
import com.andaily.infrastructure.DateUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * 15-3-14
 *
 * @author Shengzhao Li
 */
public class MonitoringReminderLogDto extends AbstractDto {


    private String createTime;

    private FrequencyMonitorLogDto monitorLogDto;

    private String instanceGuid;
    private String instanceName;

    private boolean changeNormal;

    private String receiveEmail;

    private String emailContent;


    public MonitoringReminderLogDto() {
    }

    public MonitoringReminderLogDto(MonitoringReminderLog log) {
        super(log.guid());
        this.createTime = DateUtils.toDateTime(log.createTime());
        this.monitorLogDto = new FrequencyMonitorLogDto(log.monitorLog());

        final ApplicationInstance instance = log.instance();
        this.instanceGuid = instance.guid();
        this.instanceName = instance.instanceName();

        this.changeNormal = log.changeNormal();
        this.emailContent = log.emailContent();
        this.receiveEmail = log.receiveEmail();
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public FrequencyMonitorLogDto getMonitorLogDto() {
        return monitorLogDto;
    }

    public void setMonitorLogDto(FrequencyMonitorLogDto monitorLogDto) {
        this.monitorLogDto = monitorLogDto;
    }

    public String getInstanceGuid() {
        return instanceGuid;
    }

    public void setInstanceGuid(String instanceGuid) {
        this.instanceGuid = instanceGuid;
    }

    public String getInstanceName() {
        return instanceName;
    }

    public void setInstanceName(String instanceName) {
        this.instanceName = instanceName;
    }

    public boolean isChangeNormal() {
        return changeNormal;
    }

    public void setChangeNormal(boolean changeNormal) {
        this.changeNormal = changeNormal;
    }

    public String getReceiveEmail() {
        return receiveEmail;
    }

    public void setReceiveEmail(String receiveEmail) {
        this.receiveEmail = receiveEmail;
    }

    public String getEmailContent() {
        return emailContent;
    }

    public void setEmailContent(String emailContent) {
        this.emailContent = emailContent;
    }

    public static List<MonitoringReminderLogDto> toDtosa(List<MonitoringReminderLog> logs) {
        List<MonitoringReminderLogDto> dtos = new ArrayList<>(logs.size());
        for (MonitoringReminderLog log : logs) {
            dtos.add(new MonitoringReminderLogDto(log));
        }
        return dtos;
    }
}

src/main/java/com/andaily/domain/dto/log/ReminderLogListDto.java
package com.andaily.domain.dto.log;

import com.andaily.domain.dto.application.ApplicationInstanceDto;
import com.andaily.domain.shared.paginated.DefaultPaginated;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * 15-3-14
 *
 * @author Shengzhao Li
 */
public class ReminderLogListDto extends DefaultPaginated<MonitoringReminderLogDto> {


    private String instanceGuid;
    //1 is un-normal -> normal,0 is normal -> un-normal , otherwise all
    private int normal = -1;


    private ApplicationInstanceDto instanceDto;
    private List<ApplicationInstanceDto> instanceDtos = new ArrayList<>();


    public ReminderLogListDto() {
    }


    @Override
    public Map<String, Object> queryMap() {
        final Map<String, Object> map = super.queryMap();
        map.put("instanceGuid", instanceGuid);
        map.put("normal", normal);
        return map;
    }

    public ApplicationInstanceDto getInstanceDto() {
        return instanceDto;
    }

    public void setInstanceDto(ApplicationInstanceDto instanceDto) {
        this.instanceDto = instanceDto;
    }

    public String getInstanceGuid() {
        return instanceGuid;
    }

    public void setInstanceGuid(String instanceGuid) {
        this.instanceGuid = instanceGuid;
    }

    public int getNormal() {
        return normal;
    }

    public void setNormal(int normal) {
        this.normal = normal;
    }

    public List<ApplicationInstanceDto> getInstanceDtos() {
        return instanceDtos;
    }

    public void setInstanceDtos(List<ApplicationInstanceDto> instanceDtos) {
        this.instanceDtos = instanceDtos;
    }
}

src/main/java/com/andaily/domain/log/FrequencyMonitorLog.java
package com.andaily.domain.log;

import com.andaily.domain.AbstractDomain;
import com.andaily.domain.application.ApplicationInstance;

import javax.persistence.*;
import java.util.Date;

/**
 * 14-11-23
 * 实例每一次监控的 日志
 * 这是由定时任务每一次执行后的结果
 *
 * @author Shengzhao Li
 */
@Entity
@Table(name = "frequency_monitor_log")
public class FrequencyMonitorLog extends AbstractDomain {

    private static final long serialVersionUID = 4517860393571033878L;
    //所属实例
    @ManyToOne
    @JoinColumn(name = "instance_id")
    private ApplicationInstance instance;
    //是否正常
    @Column(name = "normal")
    private boolean normal;

    /**
     * 消耗时间 ms
     */
    @Column(name = "cost_time")
    private long costTime;

    /**
     * 响应返回的数据长度: byte
     */
    @Column(name = "response_size")
    private long responseSize;


    //备注信息
    @Column(name = "remark")
    private String remark;

    //default
    public FrequencyMonitorLog() {
    }

    public ApplicationInstance instance() {
        return instance;
    }

    public FrequencyMonitorLog instance(ApplicationInstance instance) {
        this.instance = instance;
        return this;
    }

    public boolean normal() {
        return normal;
    }

    public FrequencyMonitorLog normal(boolean normal) {
        this.normal = normal;
        return this;
    }

    public long costTime() {
        return costTime;
    }

    public FrequencyMonitorLog costTime(long costTime) {
        this.costTime = costTime;
        return this;
    }

    public String remark() {
        return remark;
    }

    public FrequencyMonitorLog remark(String remark) {
        this.remark = remark;
        return this;
    }

    public FrequencyMonitorLog createTime(Date createTime) {
        this.createTime = createTime;
        return this;
    }

    public long responseSize() {
        return responseSize;
    }

    public FrequencyMonitorLog responseSize(long responseSize) {
        this.responseSize = responseSize;
        return this;
    }
}

src/main/java/com/andaily/domain/log/LogRepository.java
package com.andaily.domain.log;

import com.andaily.domain.application.ApplicationInstance;
import com.andaily.domain.shared.Repository;

import java.util.Date;
import java.util.List;
import java.util.Map;

/**
 * 15-1-2
 *
 * @author Shengzhao Li
 */

public interface LogRepository extends Repository {

    List<FrequencyMonitorLog> findFrequencyMonitorLogList(Map<String, Object> map);

    int totalFrequencyMonitorLogList(Map<String, Object> map);

    List<ApplicationInstance> findHadLogInstances();

    List<FrequencyMonitorLog> findLatestFrequencyMonitorLogs(ApplicationInstance instance, int maxResult);

    /**
     * Find  FrequencyMonitorLogs that larger than  minCreateTime and instance.guid =  instanceGuid
     *
     * @param instanceGuid  instanceGuid
     * @param minCreateTime minCreateTime
     * @return List of FrequencyMonitorLog
     */
    List<FrequencyMonitorLog> findFrequencyMonitorLogs(String instanceGuid, String minCreateTime);

    List<ApplicationInstance> findHadLogInstancesByEnabled(boolean enabled);

    FrequencyMonitorLog findLastLogByCurrentLog(FrequencyMonitorLog currentLog);

    FrequencyMonitorLog findLastNotNormalFrequencyMonitorLog(String instanceGuid);

    int amountOfInstanceMonitorLogs(String instanceGuid, boolean normal);

    int totalMonitoringReminderLogs(String instanceGuid);

    int amountOfMonitoringReminderLogs(String instanceGuid, boolean changeNormal);

    Date findFirstMonitoringLogTime(String instanceGuid, boolean normal);

    Date findFirstMonitoringLogTimeAfterSpecifyTime(String instanceGuid, Date specifyTime);

    List<FrequencyMonitorLog> findHBSearchMonitorLogs(Map<String, Object> map);

    int totalHBSearchMonitorLogs(Map<String, Object> map);

    List<MonitoringReminderLog> findMonitoringReminderLogList(Map<String, Object> map);

    int totalMonitoringReminderLogList(Map<String, Object> map);

    List<ApplicationInstance> findDistinctReminderLogInstances();
}

src/main/java/com/andaily/domain/log/reminder/PerMonitoringReminderChecker.java
package com.andaily.domain.log.reminder;

import com.andaily.domain.log.FrequencyMonitorLog;
import com.andaily.domain.log.LogRepository;
import com.andaily.domain.shared.BeanProvider;

/**
 * @author Shengzhao Li
 */
public class PerMonitoringReminderChecker {

    private transient LogRepository logRepository = BeanProvider.getBean(LogRepository.class);
    private final FrequencyMonitorLog monitorLog;

    public PerMonitoringReminderChecker(FrequencyMonitorLog monitorLog) {
        this.monitorLog = monitorLog;
    }


    /**
     * If the last FrequencyMonitorLog normal == current normal, not need reminder,
     * If the last is null, check current normal is false or not
     * otherwise, need reminder
     *
     * @return True is need, otherwise false
     */
    public boolean isNeedReminder() {
        FrequencyMonitorLog lastLog = logRepository.findLastLogByCurrentLog(monitorLog);
        if (lastLog == null) {
            return !monitorLog.normal();
        } else {
            return lastLog.normal() != monitorLog.normal();
        }
    }
}

src/main/java/com/andaily/web/controller/LogController.java
package com.andaily.web.controller;

import com.andaily.domain.dto.log.FrequencyMonitorLogListDto;
import com.andaily.domain.dto.log.ReminderLogListDto;
import com.andaily.service.LogService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;

/**
 * 15-2-13
 *
 * @author Shengzhao Li
 */
@Controller
@RequestMapping("log/")
public class LogController {


    @Autowired
    private LogService logService;


    @RequestMapping("list.hb")
    public String listLogs(FrequencyMonitorLogListDto listDto, Model model) {
        logService.loadFrequencyMonitorLogListDto(listDto);
        model.addAttribute("listDto", listDto);
        return "log/log_list";
    }


    @RequestMapping("reminder_list.hb")
    public String reminderLogs(ReminderLogListDto listDto, Model model) {
        logService.loadReminderLogListDto(listDto);
        model.addAttribute("listDto", listDto);
        return "log/reminder_logs";
    }

}

src/main/webapp/WEB-INF/jsp/log/log_list.jsp
<%--
 * 
 * @author Shengzhao Li
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fun" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="custom" %>
<%@ taglib prefix="dis" uri="http://displaytag.sf.net" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>Monitor Log</title>
</head>
<body>
<%--Alert--%>
<%--<div class="row">--%>
<%--<div class="col-md-12">--%>
<%--<div class="alert alert-success" style="display: none;">--%>
<%--<button type="button" class="close" data-dismiss="alert">&times;</button>--%>
<%--<div><em class="fui-check-circle"></em>--%>
<%--<span id="saveInstanceOK" style="display: none;">Save instance successful</span>--%>
<%--</div>--%>
<%--</div>--%>
<%----%>
<%--</div>--%>
<%--</div>--%>
<div class="row">
    <div class="col-md-10">
        <form class="form-inline" role="form" action="" id="filterForm">
            <div class="form-group">
                <select name="instanceGuid" class="form-control">
                    <option value="">All instances</option>
                    <c:forEach items="${listDto.instanceDtos}" var="st">
                        <option value="${st.guid}" ${st.guid eq listDto.instanceGuid?'selected':''}>${st.instanceName}</option>
                    </c:forEach>
                </select>
            </div>
            <div class="form-group">
                <select name="normal" class="form-control">
                    <option value="0">All statuses</option>
                    <option value="1" ${listDto.normal eq 1?'selected':''}>Normal</option>
                    <option value="2" ${listDto.normal eq 2?'selected':''}>Not normal</option>
                </select>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon">order by</div>
                    <select name="orderItem" class="form-control">
                        <c:forEach items="${listDto.orderItems}" var="item">
                            <option value="${item.value}" ${item eq listDto.orderItem?'selected':''}>${item.label}</option>
                        </c:forEach>
                    </select>
                </div>
            </div>
            <button type="submit" class="btn"><i class="fui-search"></i></button>
            <strong>${listDto.totalSize}</strong> log(s)
        </form>
    </div>
    <div class="col-md-2">
        &nbsp;
    </div>
</div>

<c:if test="${not empty listDto.instanceDto}">
    <custom:log_instance_details d="${listDto.instanceDto}"/>
</c:if>

<div class="row">
    <div class="col-md-12">
        <table class="table table-striped table-hover">
            <thead>
            <tr>
                <th>Instance</th>
                <th>Log Time</th>
                <th><abbr title='Connection Time(ms)'>Conn Time(ms)</abbr></th>
                <th><abbr title='Response Data Size(KB)'>Resp Size(KB)</abbr></th>
                <th>Remark</th>
            </tr>
            </thead>
            <tbody>
            <c:forEach items="${listDto.listGroupResults}" var="gro">
                <tr>
                    <td colspan="5">
                        <strong class="text-info">${gro.key}</strong>
                    </td>
                </tr>
                <c:forEach items="${gro.results}" var="d">
                    <tr class="${d.normal?'':'text-danger'}">
                        <td><a href="${contextPath}/monitoring/${d.instanceGuid}.hb">${d.instanceName}</a></td>
                        <td>${d.createTime}</td>
                        <td>${d.costTime}</td>
                        <td>${d.responseSizeAsKB}</td>
                        <td>
                            <custom:substring_remark d="${d}"/>
                        </td>
                    </tr>
                </c:forEach>
            </c:forEach>
            </tbody>
        </table>


        <dis:table list="${listDto}" id="d" form="filterForm" class="table hidden">
            <dis:column property="guid"/>
        </dis:table>
    </div>
</div>

</body>
</html>

src/main/webapp/WEB-INF/jsp/log/reminder_logs.jsp
<%--
 * 
 * @author Shengzhao Li
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fun" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="custom" %>
<%@ taglib prefix="dis" uri="http://displaytag.sf.net" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>Reminder Log</title>
</head>
<body>

<div class="row">
    <div class="col-md-10">
        <form class="form-inline" role="form" action="" id="filterForm">
            <div class="form-group">
                <select name="instanceGuid" class="form-control">
                    <option value="">All instances</option>
                    <c:forEach items="${listDto.instanceDtos}" var="st">
                        <option value="${st.guid}" ${st.guid eq listDto.instanceGuid?'selected':''}>${st.instanceName}</option>
                    </c:forEach>
                </select>
            </div>
            <div class="form-group">
                <select name="normal" class="form-control">
                    <option value="-1">All statuses</option>
                    <option value="0" ${listDto.normal eq 0?'selected':''}>Normal -> Un-Normal</option>
                    <option value="1" ${listDto.normal eq 1?'selected':''}>Un-Normal -> Normal</option>
                </select>
            </div>
            <button type="submit" class="btn"><i class="fui-search"></i></button>
            <strong>${listDto.totalSize}</strong> log(s)
        </form>
    </div>
    <div class="col-md-2">
        &nbsp;
    </div>
</div>

<c:if test="${not empty listDto.instanceDto}">
    <custom:log_instance_details d="${listDto.instanceDto}"/>
</c:if>

<div class="row">
    <div class="col-md-12">
        <dis:table list="${listDto}" id="d" form="filterForm" class="table table-striped table-hover">
            <dis:column title="Instance">
                <a href="${contextPath}/monitoring/${d.instanceGuid}.hb">${d.instanceName}</a>
            </dis:column>
            <dis:column title="Reminder Time" property="createTime"/>
            <dis:column title="Status">
                <c:if test="${d.changeNormal}">
                    <em class="fui-checkbox-checked text-success" title="Restore to normal"></em>
                </c:if>
                <c:if test="${not d.changeNormal}">
                    <em class="fui-stumbleupon text-warning" title="Change to un-normal"></em>
                </c:if>
            </dis:column>
            <dis:column title="Email Address">
                <a href="mailto:${d.receiveEmail}" class="text-info">${d.receiveEmail}</a>
                &nbsp;
                <a title="Show Email Content" class="showMailContent" href="javascript:void(0)"><em
                        class="fui-mail"></em></a>

                <div class="hidden">
                        ${d.emailContent}
                </div>
            </dis:column>
        </dis:table>

    </div>
</div>

<script>
    $(function () {
        new ReminderLogs();
    })
</script>
</body>
</html>