src/main/java/com/andaily/domain/dto/HBSearchDto.java
package com.andaily.domain.dto;

import com.andaily.domain.shared.paginated.DefaultPaginated;
import com.andaily.service.operation.search.ApplicationInstanceSearcher;
import com.andaily.service.operation.search.HBSearcher;
import com.andaily.service.operation.search.MonitorLogSearcher;

import java.util.Map;

/**
 * 15-3-13
 *
 * @author Shengzhao Li
 */
public class HBSearchDto extends DefaultPaginated<HBSearchResultDto> {

    private static final HBSearchType DEFAULT_SEARCH_TYPE = HBSearchType.INSTANCE;

    private String key;
    private HBSearchType searchType = DEFAULT_SEARCH_TYPE;

    public HBSearchDto() {
    }

    @Override
    public Map<String, Object> queryMap() {
        final Map<String, Object> map = super.queryMap();
        map.put("key", key);
        return map;
    }

    public HBSearchType[] getSearchTypes() {
        return HBSearchType.values();
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public HBSearchType getSearchType() {
        if (searchType == null) {
            return DEFAULT_SEARCH_TYPE;
        }
        return searchType;
    }

    public void setSearchType(HBSearchType searchType) {
        this.searchType = searchType;
    }

    public static enum HBSearchType {
        INSTANCE("Instance") {
            @Override
            public HBSearcher resolveSearcher() {
                return new ApplicationInstanceSearcher();
            }
        },
        MONITOR_LOG("MonitorLog") {
            @Override
            public HBSearcher resolveSearcher() {
                return new MonitorLogSearcher();
            }
        };

        private String label;

        private HBSearchType(String label) {
            this.label = label;
        }

        public abstract HBSearcher resolveSearcher();


        public boolean isInstance() {
            return INSTANCE.equals(this);
        }

        public boolean isMonitorLog() {
            return MONITOR_LOG.equals(this);
        }

        public String getLabel() {
            return label;
        }
    }
}

src/main/java/com/andaily/domain/dto/IndexDto.java
package com.andaily.domain.dto;

import java.util.ArrayList;
import java.util.List;

/**
 * @author Shengzhao Li
 */
public class IndexDto extends AbstractDto {

    //default show latest 20  times data
    private int maxResult = 20;

    private boolean enabled = true;

    private List<IndexInstanceDto> instanceDtos = new ArrayList<>();


    public IndexDto() {
    }

    public List<IndexInstanceDto> getInstanceDtos() {
        return instanceDtos;
    }

    public boolean isEmployInstances() {
        return instanceDtos.isEmpty();
    }

    public int getMaxResult() {
        return maxResult;
    }

    public void setMaxResult(int maxResult) {
        this.maxResult = maxResult;
    }

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }
}

src/main/webapp/WEB-INF/jsp/index.jsp
<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>Monitoring</title>
</head>
<body>
<c:if test="${indexDto.employInstances}" var="emptyInstances">
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-info" role="alert">
                <strong class="fui-info-circle"></strong>
                Not enabled any instance to monitoring yet. Now create the first <a
                    href="${contextPath}/instance/instance_form.hb">new instance</a> or go to <a
                    href="${contextPath}/instance/list.hb">instances</a> enable it.
            </div>
        </div>
    </div>
</c:if>

<c:if test="${not emptyInstances}">
    <div class="row">
        <div class="col-md-10">
            <form class="form-inline" role="form" action="" id="filterForm">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon">Per show</div>
                        <select name="maxResult" class="form-control">
                            <c:forEach begin="10" end="50" step="10" var="i">
                                <option value="${i}" ${i == indexDto.maxResult?'selected':''}>${i}</option>
                            </c:forEach>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" id="enabled" ${indexDto.enabled?'checked':''}/>Monitoring
                            <input type="hidden" name="enabled" value="${indexDto.enabled}"/>
                        </label>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-2">
            <div class="pull-right">
                <strong>${indexDto.instanceDtos.size()}</strong> instance(s)
            </div>
        </div>
    </div>

    <c:forEach items="${indexDto.instanceDtos}" var="ins" varStatus="s">
        <div class="row">
            <hr/>
            <div class="col-md-12">
                <h4><c:if test="${ins.enabled}"><em class="fui-time text-success" title="Monitoring"></em></c:if>
                    <a href="${contextPath}/monitoring/${ins.guid}.hb">${ins.instanceName}</a>
                    <small><a href="${ins.monitorUrl}" target="_blank" class="text-muted">${ins.monitorUrl}</a>
                        [${ins.requestMethod}]
                    </small>
                </h4>

                <div id="chart${s.index}" style="height:300px"></div>
            </div>
        </div>

    </c:forEach>

    <script src="${contextPath}/resources/js/echarts/echarts.js"></script>
    <script>
        require.config({
            paths:{
                echarts:'${contextPath}/resources/js/echarts'
            }
        });
        require(
                [
                    'echarts',
                    'echarts/chart/bar',
                    'echarts/chart/line'
                ],
                function (ec) {
                    <c:forEach items="${indexDto.instanceDtos}" var="ins" varStatus="s">
                    var option${s.index} = {
                        title:{
                            text:'${ins.instanceName}',
                            subtext:'Frequency: ${ins.frequency.seconds}s  Max-Conn: ${ins.maxConnectionSeconds}s Request-Method: ${ins.requestMethod}'
                        },
                        tooltip:{
                            trigger:'axis'
                        },
                        legend:{
                            data:['Conn Time(ms)']
                        },
                        toolbox:{
                            show:true,
                            feature:{
                                mark:{show:false},
                                dataView:{show:false, readOnly:false},
                                magicType:{show:true, type:['line', 'bar']},
                                restore:{show:true},
                                saveAsImage:{show:true}
                            }
                        },
                        xAxis:[
                            {
                                type:'category',
                                data:${ins.categoryData}
                            }
                        ],
                        yAxis:[
                            {
                                type:'value'
                            }
                        ],
                        series:[
                            {
                                name:'Conn Time(ms)',
                                type:'line',
                                data:${ins.seriesData},
                                markLine:{
                                    data:[
                                        {type:'average', name:'Average Conn Time'}
                                    ]
                                }
                            }
                        ]
                    };

                    var myChart${s.index} = ec.init(document.getElementById('chart${s.index}'));
                    myChart${s.index}.setOption(option${s.index});
                    myChart${s.index}.setTheme('macarons');

                    var lastLogDate${s.index} = '${ins.lastLogDate}';
                    setInterval(function () {
                        $.get("load_addition_monitor_logs.hb", {lastLogDate:lastLogDate${s.index}, guid:'${ins.guid}'}, function (data) {
                            myChart${s.index}.addData(eval(data.additionData));
                            lastLogDate${s.index} = data.lastLogDate;
                        });

                    }, ${ins.intervalTime});
                    </c:forEach>
                }
        );

    </script>
</c:if>

<script>
    $(function () {
        new Index('${param.alert}');
    });
</script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/monitoring_instance.jsp
<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>Monitoring [${instanceDto.instanceName}]</title>
</head>
<body>

<div class="row">
    <h4><c:if test="${instanceDto.enabled}"><em class="fui-time text-success"
                                                title="Monitoring"></em></c:if>
        ${instanceDto.instanceName}</h4>

    <div class="col-md-12">
        <div id="chart" style="height:400px"></div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <ul class="list-group">
            <li class="list-group-item">
                Monitor URL: <a href="${instanceDto.monitorUrl}"
                                target="_blank">${instanceDto.monitorUrl}</a> <span
                    class="text-info">[${instanceDto.requestMethod}]</span>
            </li>
            <c:if test="${not empty instanceDto.contentType}">
                <li class="list-group-item">
                    ContentType: <span class="text-info">${instanceDto.contentType}</span>
                </li>
            </c:if>
            <li class="list-group-item">
                Frequency: <span class="text-info">${instanceDto.frequency.seconds}s</span>
            </li>
            <li class="list-group-item">
                <abbr title='Max Connection Time(s)'>Max Conn(s)</abbr>: <span
                    class="text-info">${instanceDto.maxConnectionSeconds}s</span>
            </li>
            <li class="list-group-item">
                Email: <span class="text-info">${instanceDto.email}</span>
            </li>
            <li class="list-group-item">
                Remark: <span class="text-info">${instanceDto.remark}</span>
            </li>
        </ul>
    </div>
    <div class="col-md-6">
        <img src="${contextPath}/resources/images/loading_64.gif" class="img-responsive"/>
        <%--Ajax load data--%>
        <div id="staticsDiv"></div>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <div class="text-center">
            <a href="javascript:history.back();" class="btn btn-inverse">Back</a>
        </div>
    </div>
</div>


<script src="${contextPath}/resources/js/echarts/echarts.js"></script>
<script>
    require.config({
        paths:{
            echarts:'${contextPath}/resources/js/echarts'
        }
    });
    require(
            [
                'echarts',
                'echarts/chart/bar',
                'echarts/chart/line'
            ],
            function (ec) {

                var option0 = {
                    title:{
                        text:'${instanceDto.instanceName}',
                        subtext:'Frequency: ${instanceDto.frequency.seconds}s  Max-Conn: ${instanceDto.maxConnectionSeconds}s Request-Method: ${instanceDto.requestMethod}'
                    },
                    tooltip:{
                        trigger:'axis'
                    },
                    legend:{
                        data:['Conn Time(ms)']
                    },
                    toolbox:{
                        show:true,
                        feature:{
                            mark:{show:false},
                            dataView:{show:false, readOnly:false},
                            magicType:{show:true, type:['line', 'bar']},
                            restore:{show:true},
                            saveAsImage:{show:true}
                        }
                    },
                    xAxis:[
                        {
                            type:'category',
                            data:${instanceDto.categoryData}
                        }
                    ],
                    yAxis:[
                        {
                            type:'value'
                        }
                    ],
                    series:[
                        {
                            name:'Conn Time(ms)',
                            type:'line',
                            data:${instanceDto.seriesData},
                            markLine:{
                                data:[
                                    {type:'average', name:'Average Conn Time'}
                                ]
                            }
                        }
                    ]
                };

                var myChart0 = ec.init(document.getElementById('chart'));
                myChart0.setOption(option0);
                myChart0.setTheme('macarons');

                var lastLogDate0 = '${instanceDto.lastLogDate}';
                setInterval(function () {
                    $.get("../load_addition_monitor_logs.hb", {lastLogDate:lastLogDate0, guid:'${instanceDto.guid}'}, function (data) {
                        myChart0.addData(eval(data.additionData));
                        lastLogDate0 = data.lastLogDate;
                    });

                }, ${instanceDto.intervalTime});
            }
    );

    new MonitoringInstance('${instanceDto.guid}');
</script>

</body>
</html>

src/main/webapp/WEB-INF/jsp/search_result.jsp
<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="dis" uri="http://displaytag.sf.net" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="custom" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>Search by [${searchDto.key}]</title>

    <style>
        .list-group li:hover {
            background-color: #f9f9f9;
        }
    </style>
</head>
<body>

<div class="row">
    <div class="col-md-12">
        <form class="form-inline" role="form" action="" id="filterForm">
            <div class="input-group">
                <input type="text" name="key" value="${searchDto.key}" class="form-control" placeholder="Search"/>
                 <span class="input-group-btn">
                       <button type="submit" class="btn"><span class="fui-search"></span></button>
                  </span>
            </div>
            <input type="hidden" id="searchType" name="searchType" value="${searchDto.searchType}"/>
            Total: <strong>${searchDto.totalSize}</strong>
        </form>
    </div>
</div>

<div class="row" style="margin-top: 10px;">
    <div class="col-md-12">
        <ul class="nav nav-tabs">
            <c:forEach items="${searchDto.searchTypes}" var="t">
                <li role="presentation" class="${t eq searchDto.searchType?'active':''}"><a
                        href="javascript:void(0);" sType=${t}>${t.label}</a>
                </li>
            </c:forEach>
        </ul>
        <div style="margin-top: 5px;">
            <%--instance--%>
            <c:if test="${searchDto.searchType.instance}">
                <c:if test="${empty searchDto.list}">
                    <div class="well well-sm text-muted">Search result is empty.</div>
                </c:if>
                <c:if test="${not empty searchDto.list}">
                    <ul class="list-group">
                        <c:forEach items="${searchDto.list}" var="d">
                            <custom:instance_group_item d="${d.instanceDto}"/>
                        </c:forEach>
                    </ul>
                    <%--pagination--%>
                    <dis:table list="${searchDto}" id="d" form="filterForm"
                               class="table table-striped table-hover hidden">
                        <dis:column property="guid"/>
                    </dis:table>
                </c:if>
            </c:if>

            <%--monitorLog--%>
            <c:if test="${searchDto.searchType.monitorLog}">
                <dis:table list="${searchDto}" id="d" form="filterForm" class="table table-striped table-hover">
                    <dis:column title="Instance" class="${d.monitorLogDto.normal?'':'text-danger'}">
                        <a href="${contextPath}/monitoring/${d.monitorLogDto.instanceGuid}.hb">${d.monitorLogDto.instanceName}</a>
                    </dis:column>
                    <dis:column title="Log Time" property="monitorLogDto.createTime"
                                class="${d.monitorLogDto.normal?'':'text-danger'}"/>
                    <dis:column title="<abbr title='Connection Time(ms)'>Conn Time(ms)</abbr>"
                                property="monitorLogDto.costTime"
                                class="${d.monitorLogDto.normal?'':'text-danger'}"/>
                    <dis:column title="<abbr title='Response Data Size(KB)'>Resp Size(KB)</abbr>"
                                property="monitorLogDto.responseSizeAsKB"
                                class="${d.monitorLogDto.normal?'':'text-danger'}"/>
                    <dis:column title="Remark" class="${d.monitorLogDto.normal?'':'text-danger'}">
                        <custom:substring_remark d="${d.monitorLogDto}"/>
                    </dis:column>
                </dis:table>
            </c:if>
        </div>
    </div>
</div>

<script>
    $(function () {
        new SearchResult();
    });
</script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/user_profile.jsp
<%--
 * 
 * @author Shengzhao Li
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fun" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>User Profile</title>
</head>
<body>
<%--Alert--%>
<div class="row">
    <div class="col-md-12">
        <div class="alert alert-success" style="display: none;">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <div><em class="fui-check-circle"></em>
                <span id="updateProfileOK" style="display: none;">Update profile successful</span>
            </div>
        </div>
    </div>
</div>

<div>
    <div class="row">
        <div class="col-md-12">
            <h4>User Profile</h4>
            <form:form commandName="formDto" cssClass="form-horizontal">
                <div class="form-group">
                    <label class="col-sm-2 control-label">Username</label>

                    <div class="col-sm-8">
                        <p class="form-control-static">${SPRING_SECURITY_CONTEXT.authentication.principal.username}</p>
                    </div>
                </div>

                <div class="form-group">
                    <label for="oldPassword" class="col-sm-2 control-label">Old Password</label>

                    <div class="col-sm-8">
                        <form:password path="oldPassword" id="oldPassword" cssClass="form-control"
                                       placeholder="Input old pasword" required="true" maxlength="255"/>
                        <p class="help-block">Input old password</p>
                        <form:errors path="oldPassword" cssClass="text-danger"/>
                    </div>
                </div>

                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">New Password</label>

                    <div class="col-sm-8">
                        <form:password path="password" id="password" cssClass="form-control"
                                       placeholder="Input new pasword" required="true" maxlength="255"/>
                        <p class="help-block">New password length >= 6</p>
                        <form:errors path="password" cssClass="text-danger"/>
                    </div>
                </div>

                <div class="form-group">
                    <label for="rePassword" class="col-sm-2 control-label">Re-New Password</label>

                    <div class="col-sm-8">
                        <form:password path="rePassword" id="rePassword" cssClass="form-control"
                                       placeholder="Input new pasword again" required="true" maxlength="255"/>
                        <p class="help-block">Input new password again</p>
                        <form:errors path="rePassword" cssClass="text-danger"/>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary"><em class="fui-check-circle"></em> Update
                        </button>
                    </div>
                </div>
            </form:form>
        </div>
    </div>
</div>

<script>
    $(function () {
        new UserProfile('${param.alert}');
    });
</script>
</body>
</html>

src/main/webapp/WEB-INF/jsp/user_register.jsp
<%--
 * 
 * @author Shengzhao Li
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fun" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>User Register</title>
</head>
<body>

<div>
    <div class="row">
        <div class="col-md-12">
            <h4>User Register</h4>
            <form:form commandName="formDto" cssClass="form-horizontal">

                <div class="form-group">
                    <label for="username" class="col-sm-2 control-label">Username</label>

                    <div class="col-sm-8">
                        <form:input path="username" id="username" cssClass="form-control"
                                    placeholder="Input username" required="true" maxlength="40"/>
                        <p class="help-block">Unique username</p>
                        <form:errors path="username" cssClass="text-danger"/>
                    </div>
                </div>

                <div class="form-group">
                    <label for="password" class="col-sm-2 control-label">Password</label>

                    <div class="col-sm-8">
                        <form:password path="password" id="password" cssClass="form-control"
                                       placeholder="Input pasword, lenth >= 6" required="true" maxlength="255"/>
                        <p class="help-block">Password length >= 6</p>
                        <form:errors path="password" cssClass="text-danger"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="rePassword" class="col-sm-2 control-label">Re-Password</label>

                    <div class="col-sm-8">
                        <form:password path="rePassword" id="rePassword" cssClass="form-control"
                                       placeholder="Input pasword again" required="true" maxlength="255"/>
                        <p class="help-block">Input the password again</p>
                        <form:errors path="rePassword" cssClass="text-danger"/>
                    </div>
                </div>

                <div class="form-group">
                    <label for="email" class="col-sm-2 control-label">Email</label>

                    <div class="col-sm-8">
                        <form:input path="email" id="email" cssClass="form-control"
                                    placeholder="Input email" maxlength="255" required="true"/>
                        <p class="help-block">Your email address, required.</p>
                        <form:errors path="email" cssClass="text-danger"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="phone" class="col-sm-2 control-label">Phone</label>

                    <div class="col-sm-8">
                        <form:input path="phone" id="phone" cssClass="form-control"
                                    placeholder="Input phone number" maxlength="255"/>
                        <p class="help-block">Your phone number, optional.</p>
                        <form:errors path="phone" cssClass="text-danger"/>
                    </div>
                </div>

                <div class="form-group">
                    <label for="captcha" class="col-sm-2 control-label">Captcha</label>

                    <div class="col-sm-8">
                        <div class="input-group">
                            <input type="text" name="${formDto.captchaKey}" class="form-control"
                                   placeholder="Input captcha" id="captcha" maxlength="10" required="required"/>
                            <span class="input-group-addon input-sm">
                                <img src="${contextPath}/captcha.hb" onclick="this.src = this.src+'?'" alt="Captcha"/>
                            </span>
                        </div>
                        <p class="help-block">Please input captcha, required.</p>
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary"><em class="fui-check-circle"></em> Register
                        </button>
                        &nbsp;<a href="${contextPath}/login.hb">Sign in</a>
                    </div>
                </div>
            </form:form>
        </div>
    </div>
</div>

</body>
</html>

src/main/webapp/WEB-INF/jsp/user_register_forbidden.jsp
<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>User Register Forbidden</title>
</head>
<body>

<div class="row">
    <div class="col-md-12">
        <div class="alert alert-danger">
            <div>
                <h4><em class="fui-info-circle"></em> OOps... </h4>
                User register is forbidden.

                <br/>
                <br/>

                <a href="javascript:history.back();">Back</a>
            </div>
        </div>
    </div>
</div>


</body>
</html>

src/main/webapp/WEB-INF/jsp/user_register_success.jsp
<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>Register Successful</title>
</head>
<body>

<div class="row">
    <div class="col-md-12">
        <div class="alert alert-success">
            <div>
                <h3><em class="fui-check-circle"></em> Congratulation!!</h3>
                Register successful.
                <br/>
                <br/>
                <a href="${contextPath}/login.hb">Sign in</a>
            </div>
        </div>
    </div>
</div>


</body>
</html>